const Data=[
    {
        id:1,
        title:'mac lap',
        category:'laptop',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://media.istockphoto.com/id/1023428598/photo/3d-illustration-laptop-isolated-on-white-background-laptop-with-empty-space-screen-laptop-at.jpg?s=612x612&w=0&k=20&c=ssK6er5v1fGpSghGiqySwoD8tn5blC7xgefQJI2xU38=",
        price:19900,
    },
      {
        id:2,
        title:'lenovo lap',
        category:'laptop',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGTLMQw6pkEeQ6GrI67s46ztTfQ76RIPoaCQ&usqp=CAU",
        price:18900,
    },
      {
        id:3,
        title:'samsung lap',
        category:'laptop',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://www.lenovo.com/medias/lenovo-laptop-thinkpad-p1-2nd-01.jpg?context=bWFzdGVyfHJvb3R8ODc1MTN8aW1hZ2UvanBlZ3xoZjAvaDFjLzE0MzMyMjYwNTgxNDA2LmpwZ3w2NmVmMzc1YTBkMGE1YWM0ZjhiM2FlMThiNDRhMTAwZDhlOTNkODk2NmU0NjhiZDUxMjMzODU2NTRmZGU4YzYw",
        price:20900,
    },
      {
        id:4,
        title:'hawiwe lap',
        category:'laptop',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://api-rayashop.freetls.fastly.net/media/catalog/product/cache/4e49ac3a70c0b98a165f3fa6633ffee1/n/a/nafsder_-_imgur.jpg",
        price:15600,
    },
      {
        id:5,
        title:'IPHONE 13pro',
        category:'phone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://m.media-amazon.com/images/I/61i8Vjb17SL._AC_UF1000,1000_QL80_.jpg",
        price:44900,
    },
      {
        id:6,
        title:'IPHONE 12',
        category:'phone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://d1jbip55yyitxr.cloudfront.net/uploads/2021/02/18115603/71MHTD3uL4L._SL1500_.jpg",
        price:32900,
    },
      {
        id:7,
        title:'IPHONE X-max',
        category:'phone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://m.media-amazon.com/images/I/41z9eQ+HvNL.jpg",
        price:17300,
    },
      {
        id:8,
        title:'IPHONE 11proMax',
        category:'phone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://api.mobilaty.com/storage/uploads/media/catalog/product/i/p/iphone-11-pro-silver_1_5.jpg",
        price:12450,
    },
      {
        id:9,
        title:'air podies v-5',
        category:'headphone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://mybay.mv/wp-content/uploads/2022/08/Airpods-3-Black-01.jpg",
        price:4900,
    },
      {
        id:10,
        title:'air podies v-6',
        category:'headphone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://as2.ae/wp-content/uploads/2022/08/apple-airpods-3-black-1.jpg",
        price:2900,
    },
      {
        id:11,
        title:'air podies v-7',
        category:'headphone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://smhttp-ssl-73217.nexcesscdn.net/pub/media/catalog/product/cache/661473ab953cdcdf4c3b607144109b90/h/p/hp252-11_1.jpg",
        price:1500,
    },
      {
        id:12,
        title:'air podies v-8',
        category:'headphone',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCX2SsD53CnW_WTJ1AXdwBToS30i17fHwILg&usqp=CAU",
        price:1230,
    },
      {
        id:13,
        title:'canion',
        category:'cam',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://m.media-amazon.com/images/I/61BKYlNqH6L._AC_UF894,1000_QL80_.jpg",
        price:49900,
    },
      {
        id:14,
        title:'mark-3',
        category:'cam',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://i.pcmag.com/imagery/reviews/04k8d8x7xJdoPQG47ebppjT-3..v1569483584.jpg",
        price:56900,
    },
      {
        id:15,
        title:'sony cam',
        category:'cam',
        des:"we are the tech store and this is the laptop which appel made last versionwe are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://images.unsplash.com/photo-1624913503273-5f9c4e980dba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bmlrb24lMjBjYW1lcmF8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
        price:33900,
    },
      {
        id:16,
        title:'ground cam',
        category:'cam',
        des:"we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://3.img-dpreview.com/files/p/articles/1111600639/images/specs.jpeg",
        price:45600,
    },
      {
        id:17,
        title:' nature cam',
        category:'cam',
        des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
        image:"https://5.imimg.com/data5/JC/ZG/WJ/SELLER-72150054/canon-5d-mark-iii-camera.jpg",
        price:34900,
    },
    {
      id:18,
      title:'power-bank ',
      category:'power',
      des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
      image:"https://media.istockphoto.com/id/1159572124/photo/silver-power-bank.jpg?s=612x612&w=0&k=20&c=BSRT2SGzyrrCPRi9hv7zxEn_2GEdrwkxm1pLAlORTds=",
      price:700,
  },
  {
    id:19,
    title:'power-bank 1000ma',
    category:'power',
    des:"we are the tech store and this is the laptop which appel made last version we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
    image:"https://www.nexgenshop.pk/wp-content/uploads/2020/02/MI-Power.jpg",
    price:300,
},
{
  id:20,
  title:'power-bank 10000',
  category:'power',
  des:"we are the tech store and this is the laptop which appel made last versionwe are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version,we are the tech store and this is the laptop which appel made last version",
  image:"https://www.kindpng.com/picc/m/390-3908560_power-bank-xiaomi-10000-mah-hd-png-download.png",
  price:600,
}
,
{
  id:21,
  title:'power-bank 10000mA',
  category:'power',
  des:"we are the tech store and this is the laptop which appel made last version",
  image:"https://www.kindpng.com/picc/m/390-3908560_power-bank-xiaomi-10000-mah-hd-png-download.png",
  price:900,
}

];
export default Data;